### ISSUE TITLE
No dashboard

### ISSUE THREAD

**Issue by symmcom** [krakendash/krakendash#34]
I am trying to setup Kraken dashboard on 1 of my ceph node. But i keep getting the following message in the browser:
ConnectionError at /krakendash/
('Connection aborted.', error(111, 'Connection refused'))
Request Method:	GET
Request URL:	http://10.0.0.202:8003/krakendash/
Django Version:	1.8.7
Exception Type:	ConnectionError
Exception Value:	
('Connection aborted.', error(111, 'Connection refused'))
Exception Location:	/usr/lib/python2.7/dist-packages/requests/adapters.py in send, line 407
Python Executable:	/usr/bin/python
Python Version:	2.7.9
Python Path:	
['/home/tools/krakendash',
 '/home/tools/krakendash/src/rgwadmin',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/pymodules/python2.7',
 '/home/tools/krakendash/kraken/..']

Any idea why and how to fix? I made sure that the port is open.

**Comment by krakendash** [comment]
Hey, sorry, missed this issue. Did you get it fixed? What happens if you telnet to that IP on that port?
