### ISSUE TITLE
erro 404 

### ISSUE THREAD

**Issue by cecarmello** [krakendash/krakendash#35]
Hi.
 I follow your instruction to install kraken dashboard into my ceph-monitor.

I just get a 404 erro page.

![image](https://cloud.githubusercontent.com/assets/17487030/13377052/81ff2e32-dda9-11e5-9df8-c123a21fca00.png)

/root/krakendash/kraken/urls.py:5: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got status.views.home). Pass the callable instead.
  url(r'^', 'status.views.home', name='home'),

/root/krakendash/kraken/urls.py:6: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got ops.views.ops). Pass the callable instead.
  url(r'^ops/', 'ops.views.ops', name='ops'),

/root/krakendash/kraken/urls.py:7: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got status.views.osd_details). Pass the callable instead.
  url(r'^osd/(\d+)/', 'status.views.osd_details', name='osd_details'),

/root/krakendash/kraken/urls.py:8: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got status.views.activity). Pass the callable instead.
  url(r'^activity/', 'status.views.activity', name='activity'),

/root/krakendash/kraken/urls.py:10: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got ops.views.user_custom). Pass the callable instead.
  name='user_custom'),

/root/krakendash/kraken/urls.py:11: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got status.views.api). Pass the callable instead.
  url(r'^api/', "status.views.api", name="api"),

/root/krakendash/kraken/urls.py:11: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^api/', "status.views.api", name="api"),

/root/krakendash/kraken/urls.py:15: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'krakendash/', include(base_urlpatterns)),

System check identified no issues (0 silenced).
February 27, 2016 - 20:23:15
Django version 1.9.2, using settings 'kraken.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

**Comment by kylpik** [comment]
if it is still actual
please use the lower version django or change a code
the structure is a little another, use http://192.168.51.110:8000/krakendash
